# Generated by Django 2.2.2 on 2019-11-13 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='postcode',
            new_name='src_postcode',
        ),
    ]
